# Generated by Django 3.0.1 on 2020-07-02 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfa_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['Note_DATE']},
        ),
        migrations.AlterField(
            model_name='recall',
            name='Recall_CODE',
            field=models.CharField(max_length=500, unique=True, verbose_name='Rückruf-Code'),
        ),
        migrations.AlterField(
            model_name='recall',
            name='Recall_DATE_COMPLETED',
            field=models.DateField(blank=True, null=True, verbose_name='Tatsächliches Fertigstellungsdatum'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='Vehicel_MAKE',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Hersteller'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='Vehicle_FIRST_REGISTRATION_DATE',
            field=models.DateField(blank=True, null=True, verbose_name='Erstzulassungsdatum'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='Vehicle_MODEL',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Modell'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='Vehicle_PLATE',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Kennzeichen'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='Vehicle_SERIES',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Baureihe'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='Vehicle_TYPE',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Typ'),
        ),
    ]
