# Generated by Django 3.0.1 on 2020-07-03 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dfa_App', '0002_auto_20200702_2227'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recall_Docs',
            new_name='Recall_Doc',
        ),
        migrations.CreateModel(
            name='Constraint',
            fields=[
                ('Constraint_ID', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('Constraint_QUERY', models.CharField(max_length=100, verbose_name='Abfrage')),
                ('Recall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dfa_App.Recall')),
            ],
        ),
    ]
