# Generated by Django 3.0.1 on 2020-07-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfa_App', '0003_auto_20200703_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='Vehicle_LAST_3_DIGGITS',
            field=models.CharField(default=666, max_length=3, verbose_name='Letzte 3 Ziffern der FIN'),
            preserve_default=False,
        ),
    ]
