# Generated by Django 3.0.1 on 2020-07-11 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfa_App', '0004_vehicle_vehicle_last_3_diggits'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='Vehicle_DATE_LAST_MILEAGE',
            field=models.DateField(blank=True, null=True, verbose_name='Datum letzter Kilometerstand'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='Vehicle_EXTERNAL_ID',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Flottennummer'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='Vehicle_LAST_MILEAGE',
            field=models.IntegerField(blank=True, null=True, verbose_name='Letzter Kilometerstand'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='Vehicle_USER',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Fahrzeugnutzer'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='Vehicle_USER_CONTACT',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Fahrzeugnutzer Ansprechpartner'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='Vehicle_USER_CONTACT_EMAIL',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Fahrzeugnutzer Ansprechpartner Email'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='Vehicle_USER_CONTACT_PHONE',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Fahrzeugnutzer Ansprechpartner Telefon'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='Vehicle_WARRENTOR',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Gewährleistungsgeber'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='Vehicle_WARRENTOR_PREFERED_CHANNEL',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Bevorzugter Kommunikationskanal'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='Vehicle_WARRENTY_END',
            field=models.DateField(blank=True, null=True, verbose_name='Gewährleistungsende'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='Vehicle_WARRENTY_PERIOD',
            field=models.IntegerField(blank=True, null=True, verbose_name='Gewährleistungszeitraum in Tagen ab Erstzulassung'),
        ),
    ]
