# Generated by Django 3.0.1 on 2020-07-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfa_App', '0005_auto_20200711_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicel_recall',
            name='VR_DATE_COMPLETED',
            field=models.DateField(blank=True, null=True, verbose_name='Fertigstellungsdatum'),
        ),
    ]
