# Generated by Django 3.0.1 on 2020-07-13 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfa_App', '0006_auto_20200712_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicel_recall',
            name='VR_STATUS',
            field=models.SmallIntegerField(choices=[(0, 'Offen'), (1, 'Vorbelegt'), (2, 'Abgeschlossen')], default=0, verbose_name='Status'),
        ),
    ]
