# Generated by Django 3.0.1 on 2020-07-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfa_App', '0007_auto_20200713_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicel_recall',
            name='id',
        ),
        migrations.AddField(
            model_name='vehicel_recall',
            name='Vehicle_Recall_ID',
            field=models.AutoField(default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
