# Generated by Django 3.0.1 on 2020-07-15 18:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dfa_App', '0008_auto_20200714_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='recall_doc',
            name='Document_UPLOAD_DATE',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Uploaddatum'),
            preserve_default=False,
        ),
    ]
