# Generated by Django 3.0.1 on 2020-07-16 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfa_App', '0009_recall_doc_document_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicel_recall',
            name='VR_DATE_CREATED',
            field=models.DateField(auto_now_add=True, verbose_name='Anlagedatum'),
        ),
    ]
