# Generated by Django 3.0.1 on 2020-07-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfa_App', '0010_auto_20200716_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='Note_DATE',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Zeitpunkt'),
        ),
    ]
