# Generated by Django 3.0.1 on 2020-07-16 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dfa_App', '0011_auto_20200716_1745'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicel_recall',
            options={'permissions': [('CanChangeAnything', 'Can change patch all fields')]},
        ),
    ]
