# Generated by Django 3.0.1 on 2020-07-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfa_App', '0012_auto_20200716_1830'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicel_recall',
            options={'permissions': [('CanChangeAnything', 'Can patch all fields')]},
        ),
        migrations.AlterField(
            model_name='note',
            name='Note_ODOMETER',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kilometerstand'),
        ),
    ]
