# Generated by Django 3.0.1 on 2020-07-29 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dfa_App', '0013_auto_20200719_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicel_recall',
            name='VR_LAST_UPDATE',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Letze Änderung'),
        ),
        migrations.AddField(
            model_name='vehicel_recall',
            name='VR_LAST_UPDATE_WORKSHOP',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dfa_App.Workshop'),
        ),
    ]
