# Generated by Django 3.0.1 on 2020-07-29 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dfa_App', '0014_auto_20200729_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicel_recall',
            name='VR_LAST_UPDATE_BY',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
