# Generated by Django 3.0.1 on 2020-08-01 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dfa_App', '0016_vehicle_vehicle_deleted'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vehicel_Recall',
            new_name='Vehicle_Recall',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='Vehicel_MAKE',
            new_name='Vehicle_MAKE',
        ),
    ]
