# Generated by Django 3.0.1 on 2020-08-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfa_App', '0017_auto_20200801_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='Workshop_DELETED',
            field=models.BooleanField(default=False, verbose_name='Gelöscht'),
        ),
    ]
