# Generated by Django 3.0.1 on 2020-08-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfa_App', '0020_auto_20200805_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recall_doc',
            name='Document_PATH',
            field=models.FileField(upload_to='C:\\Users\\felix\\Desktop\\Projects\\my_env\\dfa\\dfa_App\\media\\uploads\\documents\\', verbose_name='Upload Pfad'),
        ),
    ]
