# Generated by Django 3.0.1 on 2020-08-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfa_App', '0021_auto_20200811_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='recall_doc',
            name='Document_PUBLISH_DATE',
            field=models.DateField(blank=True, null=True, verbose_name='Veröffentlichungsdatum'),
        ),
    ]
