# Generated by Django 3.0.1 on 2020-08-14 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dfa_App', '0022_recall_doc_document_publish_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constraint',
            name='Constraint_Vehicle_EXTERNAL_ID_FROM_CHOICES',
        ),
        migrations.RemoveField(
            model_name='constraint',
            name='Constraint_Vehicle_EXTERNAL_ID_TO_CHOICES',
        ),
        migrations.RemoveField(
            model_name='constraint',
            name='Constraint_Vehicle_VIN_FROM_CHOICES',
        ),
        migrations.RemoveField(
            model_name='constraint',
            name='Constraint_Vehicle_VIN_TO_CHOICES',
        ),
    ]
