# Generated by Django 3.0.1 on 2020-08-14 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dfa_App', '0023_auto_20200814_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constraint_JSON',
            fields=[
                ('CJ_ID', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('CJ_PATH', models.FileField(upload_to='C:\\Users\\felix\\Desktop\\Projects\\my_env\\dfa\\dfa_App\\media\\constraints\\', verbose_name='Upload Pfad')),
                ('Constraint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dfa_App.Constraint')),
            ],
        ),
    ]
