# Generated by Django 3.0.1 on 2020-08-14 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfa_App', '0024_constraint_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='constraint',
            name='Constraint_PATH',
            field=models.FileField(default=1, upload_to='C:\\Users\\felix\\Desktop\\Projects\\my_env\\dfa\\dfa_App\\media\\constraints\\', verbose_name='Upload Pfad'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Constraint_JSON',
        ),
    ]
