# Generated by Django 3.0.1 on 2020-08-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfa_App', '0025_auto_20200814_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constraint',
            name='Constraint_PATH',
            field=models.FilePathField(),
        ),
    ]
