# Generated by Django 3.0.1 on 2020-08-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfa_App', '0027_auto_20200817_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constraint',
            name='Constraint_PATH',
            field=models.FilePathField(blank=True, default=None, null=True, path='C:\\Users\\felix\\Desktop\\Projects\\my_env\\dfa\\dfa_App\\media\\constraints\\'),
        ),
    ]
