# Generated by Django 3.0.1 on 2020-09-04 09:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfa_App', '0028_auto_20200817_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recall_doc',
            name='Document_PATH',
            field=models.FileField(upload_to='C:\\Users\\felix\\Desktop\\Projects\\my_env\\dfa\\dfa_App\\media\\uploads\\documents\\', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Upload Pfad'),
        ),
    ]
