# Generated by Django 3.0.1 on 2020-09-26 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dfa_App', '0031_vehicle_vehicel_current_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='Recall',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dfa_App.Recall'),
            preserve_default=False,
        ),
    ]
