# Generated by Django 3.0.1 on 2020-09-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfa_App', '0032_history_recall'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='History_CURRENT_STATE',
            field=models.SmallIntegerField(choices=[(1, 'aktuell'), (0, 'nicht aktuell')], default=1, verbose_name='Aktueller Importstatus'),
        ),
        migrations.AddField(
            model_name='history',
            name='History_DELETED',
            field=models.BooleanField(default=False, verbose_name='Gelöscht'),
        ),
    ]
