# Generated by Django 3.0.1 on 2020-09-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfa_App', '0033_auto_20200926_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='History_DATE',
            field=models.DateField(blank=True, null=True, verbose_name='Datum'),
        ),
        migrations.AlterField(
            model_name='history',
            name='History_DESCRIPTION',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='history',
            name='History_EXTERNAL_ID',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Externe ID'),
        ),
        migrations.AlterField(
            model_name='history',
            name='History_ODOMETER',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kilometerstand'),
        ),
    ]
